mariadb_node:
  hostname: 10.127.10.158
  user: root
  db_user: root
  db_password: your-sql-password
primary_master_node:
  hostname: 10.127.10.158
  user: root
  db_host: 10.127.10.158
  db_user: root
  db_password: your-sql-password
  onecloud_version: v3.9.8
  onecloud_user: demo
  onecloud_user_password: demo@123
  controlplane_host: 10.127.10.158
  controlplane_port: "6443"
  as_host: true
  as_host_on_vm: true # only for vm.
