---
- name: Add cloud rpm repository for Kylin
  get_url:
    url: https://iso.yunion.cn/kylin/v10-{{ansible_distribution_release|lower}}/3.10/{{ansible_architecture}}/kylin-yunion.repo
    dest: /etc/yum.repos.d/kylin-yunion.repo
    validate_certs: no
  become: yes
  when:
  - is_kylin_based|default(false)|bool == true

- name: Add cloud rpm repository for OpenEuler
  get_url:
    url: https://iso.yunion.cn/openeuler/{{ansible_distribution_major_version |lower}}/3.10/{{ansible_architecture}}/yunion.repo
    dest: /etc/yum.repos.d/yunion-openeuler.repo
    validate_certs: no
  become: yes
  when:
  - is_openeuler_based|default(false)|bool == true

- name: enable repo
  shell: |
    cat > /etc/yum.repos.d/yunion.repo <<EOF_MISC
    [yunion-repo-base]
    name=Packages for Yunion Multi-Cloud Platform -
    baseurl=https://iso.yunion.cn/{{ ansible_distribution| replace(' ','') | lower }}/{{ ansible_distribution_version }}/base/{{ ansible_architecture }}
    sslverify=0
    failovermethod=priority
    enabled=1
    gpgcheck=0

    [yunion-repo-updates]
    name=Yunion Bin Packages for Yunion Multi-Cloud Platform -
    baseurl=https://iso.yunion.cn/rpm-updates/{{ansible_architecture}}
    sslverify=0
    failovermethod=priority
    enabled=1
    gpgcheck=0
    EOF_MISC
  become: yes
  when:
  - ansible_distribution in ['Anolis OS', 'Rocky']

- name: make cache
  shell: |
    yum clean all
    yum -y --disablerepo='*' --enablerepo='yunion*' makecache
  become: yes
  when:
  - is_centos_based is defined

- name: install libselinux-python for arm64 centos
  yum:
    name: libselinux-python
  when:
  - is_centos_aarch64 is defined
  become: yes
