containerd_url: https://iso.yunion.cn/binaries/containerd/releases/download/v1.7.13/containerd-1.7.13-linux-{{ ansible_architecture }}.tar.gz
containerd_package_name: containerd-1.7.13-linux-{{ ansible_architecture }}

crictl_url: https://iso.yunion.cn/binaries/cri-tools/releases/download/v1.30.0/crictl-v1.30.0-linux-{{ ansible_architecture }}.tar.gz
crictl_package_name: crictl-v1.30.0-linux-{{ ansible_architecture }}

ocnet_cni_url: https://iso.yunion.cn/binaries/kubecomps/releases/download/v20240510.0/ocnet-cni-{{ ansible_architecture }}
ocnet_cni_package_name: ocnet-cni

runc_url: https://iso.yunion.cn/binaries/runc/releases/download/v1.1.12/runc.{{ ansible_architecture }}
runc_package_name: runc

