- name: Install mariadb
  package:
    name: "{{ item }}"
    state: "present"
    disablerepo: "*"
    enablerepo: "yunion-*"
  with_items:
    - mariadb-server

- name: pips for mysql/mariadb online
  pip:
    name: PyMySQL
  vars:
    ansible_python_interpreter: /usr/bin/python3
  when:
  - online_status == "online"

- name: pips for mysql/mariadb offline
  pip:
    name: PyMySQL
    extra_args: "--no-index --find-links=file://{{ offline_data_path }}/pips"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  when:
  - online_status == "offline"
  - offline_data_path is defined | length > 0
