# 默认变量
gpu_device_count: 8

# 安装包完整路径（从命令行参数传入）
# nvidia_driver_installer_path: "/root/nvidia/NVIDIA-Linux-x86_64-570.133.07.run"
# cuda_installer_path: "/root/nvidia/cuda_12.8.1_570.124.06_linux.run"
# nvidia_driver_tar_file_path: "/root/nvidia/nvidia-driver-vol.tar.gz"
