---
- name: Setup repo mirrors
  include_role:
    name: utils/mirror

- name: "Add yunion rpm repository {{ yunion_yum_repo }}"
  get_url:
    url: "{{ yunion_yum_repo }}"
    dest: /etc/yum.repos.d/yunion.repo
    force: yes
    validate_certs: no
  become: yes
  when:
  - is_centos_x86 is defined

- name: Remove the old yunion-executor-server package
  yum:
    name: yunion-executor-server
    state: absent
  when:
  - is_centos_x86 is defined

- name: Upgrade yunion common packages
  yum:
    name:
      - yunion-ocadm
      - yunion-climc
      - yunion-executor
    state: latest
    disablerepo: '*'
    enablerepo: "yunion-*"
  when:
  - is_centos_x86 is defined

- name: Restart yunion executor service
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  loop:
    - yunion-executor
