---
- name: Include utils/controlplane tasks
  include_role:
    name: utils/controlplane

- name: Upgrade ocadm packages
  yum:
    name:
      - yunion-ocadm
    disablerepo: "*"
    enablerepo: "yunion-*"
    state: latest
  when:
  - is_centos_based is defined

- name: Copy clean_k8s_obj.sed script to /tmp
  copy:
    src: "clean_k8s_obj.sed"
    dest: "/tmp/clean_k8s_obj.sed"

- name: Backup current onecloud cluster and operator resource to /opt/yunion/ocboot/_upgrade/.*
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: |
    bk_dir=/opt/yunion/ocboot/_upgrade/`date +%Y.%m.%d-%H:%M:%S`
    mkdir -p $bk_dir
    kubectl get deployment -n onecloud onecloud-operator -o yaml | sed -f /tmp/clean_k8s_obj.sed > $bk_dir/operator.yml
    kubectl get oc -n onecloud default -o yaml | sed -f /tmp/clean_k8s_obj.sed > $bk_dir/oc.yml

- name: update operator only
  shell: |
      pkill -9 ocadm || :
      /opt/yunion/bin/ocadm cluster update --operator-version {{ upgrade_onecloud_version }} \
        --version {{ upgrade_onecloud_version }} \
        --image-repository {{ image_repository | default('registry.cn-beijing.aliyuncs.com/yunion')}} \
        --operator-only \
        --wait
  # 30 minutes timeout
  async: 1800
  poll: 0

- name: Copy turn-on-operator-clear-component patch to /tmp/turn-on-operator-clear-component.patch.yml
  copy:
    src: "turn-on-operator-clear-component.patch.yml"
    dest: "/tmp/turn-on-operator-clear-component.patch.yml"

- name: Turn on operator -clear-component option
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: |
    kubectl patch deployment -n onecloud onecloud-operator --patch "$(cat /tmp/turn-on-operator-clear-component.patch.yml)" && rm -f /tmp/turn-on-operator-clear-component.patch.yml
  args:
    executable: /bin/bash

- block:
  - name: test if version file contains cloudpods-ee image
    shell: |
      cat "{{ offline_data_path }}/versions.json" |jq  '.dockers |to_entries[]' |grep -wq cloudpods-ee
    register: has_cloudpack_image
    failed_when: false
    args:
      executable: /bin/bash

  - name: patch hyper image for ee mode
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
    shell: |
      kubectl -n onecloud patch onecloudcluster default --type='json' -p '[{"op": "replace", "path": "/spec/useHyperImage", "value": true}]'
    args:
      executable: /bin/bash
    when:
    - has_cloudpack_image.rc == 0

  when:
  - offline_data_path |default("") | length > 0

# use async task to upgrade, ref: https://docs.ansible.com/ansible/latest/user_guide/playbooks_async.html
- name: primary master node | Use ocadm upgrade version "{{ current_onecloud_version }}" to "{{ upgrade_onecloud_version }}"
  shell: |
      pkill -9 ocadm || :
      /opt/yunion/bin/ocadm cluster update --operator-version {{ upgrade_onecloud_version }} \
        --version {{ upgrade_onecloud_version }} \
        --image-repository {{ image_repository | default('registry.cn-beijing.aliyuncs.com/yunion')}} \
        --wait
  # 30 minutes timeout
  async: 1800
  poll: 0
  register: ocadm_update_register

- name: >
    primary master node | Check ocadm upgrade async task.
    To watch upgrade process,
    SSH login host "{{ ansible_hostname }}" execute:
      kubectl get pods -n onecloud -w
  async_status:
    jid: "{{ ocadm_update_register.ansible_job_id }}"
  register: ocadm_update_result
  until: ocadm_update_result.finished
  retries: 30
  delay: 60

- name: Copy turn-off-operator-clear-component patch to /tmp/turn-off-operator-clear-component.patch.yml
  copy:
    src: "turn-off-operator-clear-component.patch.yml"
    dest: "/tmp/turn-off-operator-clear-component.patch.yml"

- name: Turn off operator -clear-component option
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: |
    kubectl patch deployment -n onecloud onecloud-operator --patch "$(cat /tmp/turn-off-operator-clear-component.patch.yml)" && rm -f /tmp/turn-off-operator-clear-component.patch.yml
  args:
    executable: /bin/bash
