---
is_redhat_based: true
is_centos_based: true
is_centos_aarch64: true
centos_version: 10

preinstall_packages:
    - epel-release

ovs_imported_repos:
    - https://mirror.stream.centos.org/SIGs/10-stream/nfv/{{ ansible_architecture }}/openvswitch-2/

ceph_imported_repos:
    - https://mirror.stream.centos.org/SIGs/10-stream/storage/{{ ansible_architecture }}/ceph-squid/

common_packages:
    - bash-completion
    - bridge-utils
    - chrony
    - conntrack-tools
    - curl
    - fuse
    - jq
    - kmod
    - lvm2
    - nfs-utils
    - parallel
    - rsync
    - pciutils
    - tcpdump
    - python3-libselinux
    - python3-pip
    - kernel-modules-extra-{{ ansible_kernel }}
    - "{{ yunion_qemu_package }}"

ceph_packages:
    - ceph-common

ovs_packages:
    - openvswitch3.4

common_services:
    - chronyd
    - yunion-executor

k8s_packages:
    - container-selinux
    - containerd.io
    - cri-tools
    - docker-ce
    - kubeadm-1.15.12-0
    - kubectl-1.15.12-0
    - kubelet-1.15.12-0
    - kubernetes-cni