is_debian_based: true
is_debian_based_x86: true
debian_based_arch: amd64

common_packages:
  - bash-completion
  - bridge-utils
  - conntrack-tools
  - cron
  - curl
  - dkms
  - ipset
  - ipvsadm
  - jq
  - nfs-utils
  - chrony
  - parallel
  - python-selinux
  - python-setuptools
  - python-pip
  - "{{ yunion_qemu_package }}"
  - yunion-executor
  - yunion-ovmfrpm

common_services:
  - chrony
  - yunion-executor