---
is_redhat_based: true
is_centos_based: true
is_centos_x86: true
is_centos: true
centos_version: 8

preinstall_packages:
    - epel-release

ovs_preinstall_packages:
    - centos-release-nfv-openvswitch

ceph_preinstall_packages:
    - centos-release-ceph-reef

common_packages:
    - bash-completion
    - bridge-utils
    - conntrack-tools
    - curl
    - fuse
    - jq
    - kmod
    - nfs-utils
    - parallel
    - rsync
    - tcpdump
    - python3-libselinux
    - python3-pip
    - "{{ yunion_qemu_package }}"

ceph_packages:
    - ceph-common

ovs_packages:
    - openvswitch2.15

k8s_packages:
    - container-selinux
    - containerd.io
    - cri-tools
    - docker-ce
    - kubeadm-1.15.12-0
    - kubectl-1.15.12-0
    - kubelet-1.15.12-0
    - kubernetes-cni

common_services:
    - chronyd
    - yunion-executor

