---
is_redhat_based: true
is_centos_based: true
is_centos_x86: true
is_centos: true

common_packages:
    - autogen-libopts
    - bash-completion
    - boost-iostreams
    - boost-random
    - boost-system
    - boost-thread
    - bridge-utils
    - celt051
    - ceph-common
    - conntrack-tools
    - container-selinux
    - containerd.io
    - cri-tools
    - curl
    - docker-ce
    - fuse
    - fuse-devel
    - fuse-libs
    - gssproxy
    - htop
    - ipset
    - ipvsadm
    - jq
    - keyutils
    - kmod
    - kmod-openvswitch
    - kubeadm-1.15.12-0
    - kubectl-1.15.12-0
    - kubelet-1.15.12-0
    - kubernetes-cni
    - libaio
    - libbasicobjects
    - libcollection
    - libini_config
    - libjpeg-turbo
    - libnfsidmap
    - libogg
    - libpath_utils
    - libpcap
    - librados2
    - librbd1
    - libref_array
    - libselinux-python3
    - libtirpc
    - libusb
    - libusbx
    - libverto-libevent
    - lm_sensors-libs
    - lvm2
    - nc
    - net-tools
    - nfs-utils
    - nmap-ncat
    - ntp
    - ntpdate
    - oniguruma
    - openvswitch
    - parallel
    - pciutils
    - pixman
    - python3-pip
    - python36
    - quota
    - quota-nls
    - rpcbind
    - rsync
    - socat
    - spice
    - spice-protocol
    - sysstat
    - tcp_wrappers
    - tcpdump
    - unbound
    - unbound-libs
    - usbredir
    - usbutils
    - wget
    - "{{ yunion_qemu_package }}"

common_services:
    - ntpd
    - yunion-executor

