---
is_redhat_based: true
is_centos_based: true
is_centos_aarch64: true
is_centos: true

common_packages:
  - bash-completion
  - boost-iostreams
  - boost-random
  - boost-system
  - boost-thread
  - bridge-utils
  - celt051
  - ceph-common
  - conntrack-tools
  - curl
  - fuse
  - fuse-devel
  - fuse-libs
  - gssproxy
  - htop
  - ipset
  - ipvsadm
  - jq
  - keyutils
  - kmod
  - kmod-openvswitch
  - libaio
  - libbasicobjects
  - libcollection
  - libini_config
  - libjpeg-turbo
  - libnfsidmap
  - libogg
  - libpath_utils
  - libpcap
  - librados2
  - librbd1
  - libref_array
  - libselinux-python3
  - libtirpc
  - libusb
  - libusbx
  - libverto-libevent
  - lm_sensors-libs
  - lvm2
  - nc
  - net-tools
  - nfs-utils
  - nmap-ncat
  - ntp
  - ntpdate
  - oniguruma
  - openvswitch
  - parallel
  - pciutils
  - pixman
  - quota
  - quota-nls
  - rpcbind
  - rsync
  - spice
  - spice-protocol
  - sysstat
  - tcp_wrappers
  - tcpdump
  - unbound
  - unbound-libs
  - usbredir
  - usbutils
  - wget
  - "{{ yunion_qemu_package }}"

common_services:
    - ntpd
    - yunion-executor

k8s_packages:
    - container-selinux
    - containerd.io
    - cri-tools
    - docker-ce
    - kubeadm-1.15.12-0
    - kubectl-1.15.12-0
    - kubelet-1.15.12-0
    - kubernetes-cni