is_debian_based: true
debian_based_arch: arm64

common_packages:
  - apt-transport-https
  - bash-completion
  - bridge-utils
  - ca-certificates
  - ceph-common
  - chntpw
  - conntrack
  - conntrackd
  - curl
  - dkms
  - docker-ce         #
  - git
  - glusterfs-common
  - gnupg-agent
  - gnupg2
  - ipset
  - ipvsadm
  - jq
  - kubeadm=1.15.12-00 #
  - kubectl=1.15.12-00 #
  - kubelet=1.15.12-00 #
  - libusb-1.0-0
  - libusbredirparser1
  - librbd1
  - libspice-server1
  - nfs-common
  - ntp
  - python-selinux
  - software-properties-common
  - wget
  - ovmf
  - openvswitch-switch
  - yunion-climc
  - yunion-executor
  - yunion-ocadm
  - yunion-qemu-4.2.0
  - yunion-fetcherfs

common_services:
    - ntp
    - yunion-executor
