---
latest_packages:
    - ca-certificates
    - "yunion-climc-{{ onecloud_version_abbr }}[.-]*"
    - "yunion-climc-ee-{{ onecloud_version_abbr }}[.-]*"
    - yunion-executor
    - yunion-fetcherfs
    - yunion-ovmfrpm
