---

is_redhat_based: true
is_openeuler_x86: true
is_openeuler_based: true
is_centos_based: true

common_packages:
    - bash-completion
    - boost-iostreams
    - boost-random
    - boost-system
    - boost-thread
    - bridge-utils
    - celt051
    - ceph-common
    - conntrack-tools
    - curl
    - fuse
    - fuse-devel
    - fuse-libs
    - gssproxy
    - ipset
    - ipvsadm
    - jq
    - keyutils
    - kmod
    - kmod-openvswitch
    - libbasicobjects
    - libcollection
    - libini_config
    - libjpeg-turbo
    - libnfsidmap
    - libogg
    - libpath_utils
    - libpcap
    - librados2
    - librbd1
    - libref_array
    - libtirpc
    - libusb
    - libusbx
    - libverto-libevent
    - lm_sensors-libs
    - nfs-utils
    - nmap-ncat
    - openvswitch
    - parallel
    - pixman
    - python3-libselinux
    - quota
    - quota-nls
    - rpcbind
    - rsync
    - sysstat
    - tcp_wrappers
    - tcpdump
    - unbound
    - unbound-libs
    - usbredir
    - usbutils
    - wget
    - "{{ yunion_qemu_package }}"

common_services:
    - yunion-executor

k8s_packages:
    - containerd.io
    - cri-tools
    - docker-ce
    - kubeadm-1.15.12-0
    - kubectl-1.15.12-0
    - kubelet-1.15.12-0
    - kubernetes-cni
