---

is_redhat_based: true
is_openeuler_x86: true
is_openeuler_based: true

common_packages:
  - bash-completion
  - boost-iostreams
  - boost-random
  - boost-system
  - boost-thread
  - bridge-utils
  - celt051
  - ceph-common
  - conntrack-tools
  - curl
  - docker-ce
  - fuse
  - fuse-devel
  - fuse-libs
  - gssproxy
  - ipset
  - ipvsadm
  - jq
  - keyutils
  - kmod
  - kmod-openvswitch
  - kubeadm-1.15.12-0
  - kubectl-1.15.12-0
  - kubelet-1.15.12-0
  - kubernetes-cni
  - libbasicobjects
  - libcollection
  - libini_config
  - libjpeg-turbo
  - libnfsidmap
  - libogg
  - libpath_utils
  - libpcap
  - librados2
  - librbd1
  - libref_array
  - libtirpc
  - libusb
  - libusbx
  - libverto-libevent
  - lm_sensors-libs
  - nfs-utils
  - nmap-ncat
  - openvswitch
  - parallel
  - pixman
  - python3-libselinux
  - quota
  - quota-nls
  - rpcbind
  - rsync
  - sysstat
  - tcp_wrappers
  - tcpdump
  - unbound
  - unbound-libs
  - usbredir
  - usbutils
  - wget
  - "{{ yunion_qemu_package }}"

common_services:
  #  - ntpd not for openeuler
  - yunion-executor

latest_packages:
  - ca-certificates
  - yunion-climc
  - yunion-climc-ee
  - yunion-executor
  - yunion-fetcherfs
  - yunion-ocadm
  - yunion-ovmfrpm
