---

is_redhat_based: true
is_openeuler_x86: true
is_openeuler_based: true
is_centos_based: true
centos_version: 10

common_packages:
    - bash-completion
    - bridge-utils
    - conntrack-tools
    - curl
    - fuse
    - jq
    - kmod
    - nfs-utils
    - parallel
    - rsync
    - tcpdump
    - python3-libselinux
    - "{{ yunion_qemu_package }}"

ceph_packages:
    - ceph-common

ovs_packages:
    - openvswitch

common_services:
    - yunion-executor

k8s_packages:
    - containerd.io
    - cri-tools
    - docker-ce
    - kubeadm-1.15.12-0
    - kubectl-1.15.12-0
    - kubelet-1.15.12-0
    - kubernetes-cni

