---
is_redhat_based: true
is_centos_based: true

common_packages:
    - autogen-libopts
    - bash-completion
    - boost-iostreams
    - boost-random
    - boost-system
    - boost-thread
    - bridge-utils
    - celt051
    - ceph-common
    - chrony
    - conntrack-tools
    - cri-tools
    - curl
    - docker-ce
    - fuse
    - fuse-devel
    - fuse-libs
    - gssproxy
    - htop
    - ipset
    - ipvsadm
    - jq
    - keyutils
    - kmod
    - kubeadm-1.15.12-0
    - kubectl-1.15.12-0
    - kubelet-1.15.12-0
    - kubernetes-cni
    - libaio
    - libbasicobjects
    - libcollection
    - libini_config
    - libnfsidmap
    - libogg
    - libpath_utils
    - libpcap
    - librados2
    - librbd1
    - libref_array
    - libselinux-python3
    - libtirpc
    - libusbx
    - libverto-libevent
    - lm_sensors-libs
    - lvm2
    - nc
    - net-tools
    - nfs-utils
    - nmap-ncat
    - oniguruma
    - openvswitch2.15
    - parallel
    - pciutils
    - python36
    - quota
    - quota-nls
    - rpcbind
    - rsync
    - socat
    - sysstat
    - tcp_wrappers
    - tcpdump
    - unbound
    - usbutils
    - wget
    - yunion-qemu-4.2.0

common_services:
    - chronyd
    - yunion-executor

dnf_modules:
    - container-tools
    - perl:5.26
    - perl-libwww-perl:6.34
    - perl-IO-Socket-SSL:2.066
    - virt:rhel
    - python36:3.6

