is_debian_based: true
is_ubuntu_based: true
is_ubuntu_based_riscv64: true
debian_based_arch: riscv64

common_packages:
  - apt-transport-https
  - bash-completion
  - bridge-utils
  - ceph-common
  - conntrack
  - conntrackd
  - cron
  - curl
  - dkms
  - gnupg-agent
  - gnupg2
  - ipset
  - ipvsadm
  - jq
  - nfs-common
  - chrony
  - openvswitch-switch
  - parallel
  - python3-selinux
  - software-properties-common
  #- "{{ yunion_qemu_package }}"
  #- yunion-ovmfrpm

common_services:
    - chrony
    #- yunion-executor

k8s_packages:
    - docker-ce
    #- kubeadm=1.15.12-00
    #- kubectl=1.15.12-00
    #- kubelet=1.15.12-00
