is_debian_based: true
is_ubuntu_based: true
is_ubuntu_based_aarch64: true
debian_based_arch: arm64

common_packages:
  - apt-transport-https
  - bash-completion
  - bridge-utils
  - conntrack
  - conntrackd
  - cron
  - curl
  - dkms
  - gnupg-agent
  - gnupg2
  - ipset
  - ipvsadm
  - jq
  - nfs-common
  - chrony
  - parallel
  - python3-selinux
  - software-properties-common
  - "{{ yunion_qemu_package }}"
  - yunion-ovmfrpm

ceph_packages:
    - ceph-common

ovs_packages:
    - openvswitch-switch

common_services:
    - chrony
    - yunion-executor

k8s_packages:
    - docker-ce
    - kubeadm=1.15.12-00
    - kubectl=1.15.12-00
    - kubelet=1.15.12-00
