- name: Do common setup
  include_role:
    name: common

- name: pre-install-common
  include_role:
    name: pre-install-common
  when:
  - ansible_connection is defined
  - ansible_connection == "ssh"

- name: pre-install-host
  include_role:
    name: pre-install-host
  when:
  - ansible_connection is defined
  - ansible_connection == "ssh"

- name: TCP Configuration
  include_role:
    name: tcp
  when:
    k8s_node_as_oc_controller|default(false)|bool == true

- name: construct k8s_controlplane_host
  set_fact:
    k8s_controlplane_host: "{{groups['primary_master_node'][0]}}"
  when:
    k8s_controlplane_host is not defined or k8s_controlplane_host|length == 0

- name: Add controlplane host
  add_host:
    hostname: '{{ k8s_controlplane_host }}'
    ansible_host: '{{ k8s_controlplane_host }}'
    ansible_ssh_host: '{{ k8s_controlplane_host }}'
    ansible_user: '{{ ansible_user }}'
    ansible_ssh_user: '{{ ansible_user }}'
    ansible_port: '{{ k8s_controlplane_ssh_port | default(22) }}'
    ansible_ssh_port: '{{ k8s_controlplane_ssh_port | default(22) }}'

- name: Get join token
  shell: kubeadm token create --description "ocadm-playbook-node-joining-token" --ttl 15m --print-join-command | awk '{print $5}{print $7}'
  register: K8S_JOIN_TOKEN
  delegate_to: "{{ k8s_controlplane_host }}"
  run_once: yes
  environment:
    http_proxy: ''
    https_proxy: ''
  when:
    k8s_join_token is not defined or k8s_join_token|length == 0
  changed_when: false

- name: Check node is join
  shell: test -f /etc/kubernetes/kubelet.conf
  register: kubelet_result
  ignore_errors: yes
  changed_when: false
  failed_when: false

- block:
  - name: fetch join token
    set_fact:
      k8s_join_token: "{{ K8S_JOIN_TOKEN.stdout_lines[0] }}"
    when:
      k8s_join_token is not defined or k8s_join_token|length == 0

  - name: construct controlplane endpoint
    set_fact:
      controlplane_endpoint: "{{k8s_controlplane_host}}:{{ k8s_controlplane_port | default(6443) }}"

  - name: construct join args
    set_fact:
      join_args: "join {{ controlplane_endpoint }} --token {{ k8s_join_token }} --discovery-token-unsafe-skip-ca-verification"

  - name: join node as onecloud controller
    set_fact:
      join_args: "{{ join_args }} --as-onecloud-controller"
    when:
    - k8s_node_as_oc_controller|default(false)|bool == true

  - name: join node as onecloud host agent
    set_fact:
      join_args: "{{ join_args }} --enable-host-agent"
    when:
    - join_as_host | default(false)|bool == true

  - name: join node for node-ip
    set_fact:
      join_args: "{{ join_args }} --node-ip {{ node_ip }}"
    when:
      node_ip is defined

  - name: construct host network args
    set_fact:
      join_args: "{{ join_args }} --host-networks {{ host_networks }} "
    when:
      host_networks is defined

  - name: construct hugepage args
    set_fact:
      join_args: "{{ join_args }} --enable-hugepage "
    when:
      enable_hugepage is defined

  - name: "Use 'ocadm {{ join_args }}'"
    command: "/opt/yunion/bin/ocadm {{ join_args }}"
    environment:
      http_proxy: ''
      https_proxy: ''
  when:
    kubelet_result.rc != 0

- name: Include utils/k8s/kubelet/extra-args tasks
  include_role:
    name: utils/k8s/kubelet/extra-args
