# This role contains common plays that will run on all nodes
- name: version test
  debug:
    msg: "onecloud_version: {{onecloud_version }} online_status: {{online_status}}"

- name: Install kernel-5.4.130-1.yn20230805.el7 when GE v3.10.7
  yum:
    enablerepo: "{{ (online_status != 'online') | ternary('yunion-*', omit) }}"
    disablerepo: "{{ (online_status != 'online') | ternary('*', omit) }}"
    name:
    - kernel-5.4.130-1.yn20230805.el7
    - kernel-devel-5.4.130-1.yn20230805.el7
    - kernel-headers-5.4.130-1.yn20230805.el7
  become: yes
  when:
  - onecloud_version is defined
  - onecloud_version is version('v3.10.7', '>=') or online_status == 'offline'
  retries: 3
  delay: 30
  register: install_kernel_yn20230805
  until: install_kernel_yn20230805.rc == 0

- name: Install kernel-5.4.130-1.yn20221208.el7 when LE v3.10.6
  yum:
    enablerepo: "{{ (online_status != 'online') | ternary('yunion-*', omit) }}"
    disablerepo: "{{ (online_status != 'online') | ternary('*', omit) }}"
    name:
    - kernel-5.4.130-1.yn20221208.el7
    - kernel-devel-5.4.130-1.yn20221208.el7
    - kernel-headers-5.4.130-1.yn20221208.el7
  become: yes
  when:
  - onecloud_version is defined
  - onecloud_version is version('v3.10.7', '<')
  retries: 3
  delay: 30
  register: install_kernel_yn20221208
  until: install_kernel_yn20221208.rc == 0

- name: SSH Reboot system if not cloud kernel, it should take a few minutes...
  reboot:
    reboot_timeout:  900 # 15 mins
    connect_timeout: 900 # 15 mins
    msg: "rebooting host to enable cloud kernel ... please wait... "
    test_command: "uname -r | grep -qE '{{ kernel_regex }}'   "
  become: yes
  when:
    - is_yunion_kernel_running.rc != 0
    - is_controller_node is not defined or is_controller_node|default(false)|bool == false
    - ansible_connection == "ssh"

- name: Local Reboot system if not cloud kernel, it should take a few minutes...
  command: reboot
  become: yes
  when:
    - is_yunion_kernel_running.rc != 0
    - is_controller_node is not defined or is_controller_node|default(false)|bool == false
    - ansible_connection == "local"
